spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/flosdev
    username: dev
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:import.sql
  security:
    oauth2:
      client:
        registration:
          naver:
            redirectUri: "http://localhost:8080/login/oauth2/code/naver"
          kakao:
            redirectUri: "http://localhost:8080/login/oauth2/code/kakao"
file:
  dir: C:\flos\