 spring:
  redis:
    host: i8b210.p.ssafy.io
    port: 6379
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i8b210.p.ssafy.io:3306/flosdev
    username: dev
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          naver:
            redirectUri: "http://i8b210.p.ssafy.io:8080/login/oauth2/code/naver"
          kakao:
            redirectUri: "http://i8b210.p.ssafy.io:8080/login/oauth2/code/kakao"
file:
  dir: /home/flos/